CREATE TABLE mountains (
	id INT(10) NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) DEFAULT NULL,
	title LONGTEXT DEFAULT NULL,
	site LONGTEXT DEFAULT NULL,
    height VARCHAR(10) DEFAULT NULL,
    feature LONGTEXT DEFAULT NULL,
    overview LONGTEXT DEFAULT NULL,
    information LONGTEXT DEFAULT NULL,
    leadtime LONGTEXT DEFAULT NULL,
    x_coord VARCHAR(30) DEFAULT NULL,
    y_coord VARCHAR(30) DEFAULT NULL,
	reg_date DATE DEFAULT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE mt_images (
	id INT(10) NOT NULL AUTO_INCREMENT,
	mt_id INT(10) NOT NULL,
    link LONGTEXT DEFAULT NULL,
	reg_date DATE DEFAULT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (mt_id)
    REFERENCES mountains(id)
);