CREATE TABLE skyscrapers (
	id INT(10) NOT NULL AUTO_INCREMENT,
	ranking NVARCHAR(100) DEFAULT NULL,
	building_name NVARCHAR(100) DEFAULT NULL,
	city_name NVARCHAR(100) DEFAULT NULL,
	country NVARCHAR(100) DEFAULT NULL,
	height_m NVARCHAR(100) DEFAULT NULL,
	height_ft NVARCHAR(100) DEFAULT NULL,
	floor NVARCHAR(100) DEFAULT NULL,
	completion_year NVARCHAR(100) DEFAULT NULL,
	material NVARCHAR(100) DEFAULT NULL,
	category NVARCHAR(100) DEFAULT NULL,
	thumbnail LONGTEXT DEFAULT NULL,
	x_coord NVARCHAR(100) DEFAULT NULL,
	y_coord NVARCHAR(100) DEFAULT NULL,
	reg_date DATE DEFAULT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE bldg_images (
	id INT(10) NOT NULL AUTO_INCREMENT,
	bldg_id INT(10) NOT NULL,
	bldg_link LONGTEXT DEFAULT NULL,
	reg_date DATE DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (bldg_id)
	REFERENCES skyscrapers(id)
);

CREATE TABLE bldg_weather (
	id INT(10) NOT NULL AUTO_INCREMENT,
	bldg_id INT(10) NOT NULL,
	city_name VARCHAR(30) DEFAULT NULL,
	main_weather VARCHAR(30) DEFAULT NULL,
	temperature VARCHAR(30) DEFAULT NULL,
	feels_like VARCHAR(30) DEFAULT NULL,
	humidity VARCHAR(30) DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (bldg_id)
	REFERENCES skyscrapers(id)
);

